ALTER TABLE users MODIFY created_at DATETIME;
ALTER TABLE users MODIFY updated_at DATETIME;
ALTER TABLE books MODIFY created_at DATETIME;
ALTER TABLE books MODIFY updated_at DATETIME;
ALTER TABLE reviews MODIFY created_at DATETIME;
ALTER TABLE reviews MODIFY updated_at DATETIME;
ALTER TABLE logs MODIFY created_at DATETIME;
ALTER TABLE logs MODIFY updated_at DATETIME;